#!/bin/bash

NAME='chat'
DJANGODIR=/webapps/chat/chat
SOCKFILE=/webapps/chat/run/gunicorn.sock
USER=chat
GROUP=webapps
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=chat.settingsprod
DJANGO_ASGI_MODULE=chat.asgi
TIMEOUT=120

cd $DJANGODIR
source ../env/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

exec ../env/bin/gunicorn ${DJANGO_ASGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--timeout $TIMEOUT \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=- \
-k uvicorn.workers.UvicornWorker